# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170214_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabber',
            name='isRep',
            field=models.BooleanField(default=False),
        ),
    ]
